/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.time.Instant;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Inscrito;


import service.InscritoService;

/**
 *
 * @author Leonardo
 */
public class CadastrarInscrito extends javax.swing.JFrame {

    
    private InscritoService inscritoService = new InscritoService();
    
         
            
    public CadastrarInscrito() {
        initComponents();
        AtualizarTabela();
        LimparCampos();
        campoDataNascimentoInscrito.setMaxSelectableDate(Date.from(Instant.now()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        campoNomeInscrito = new javax.swing.JTextField();
        campoEmailInscrito = new javax.swing.JTextField();
        jLabelNomeInscrito = new javax.swing.JLabel();
        jLabelEmailInscrito = new javax.swing.JLabel();
        jLabelCpfInscrito = new javax.swing.JLabel();
        botaoCadastrar = new javax.swing.JButton();
        campoVoltarInscrito = new javax.swing.JButton();
        campoNaturalidadeInscrito = new javax.swing.JTextField();
        jLabelNaturalidadeInscrito = new javax.swing.JLabel();
        campoInstituicaoInscrito = new javax.swing.JTextField();
        jLabelInstituicaoInscrito = new javax.swing.JLabel();
        campoDataNascimentoInscrito = new com.toedter.calendar.JDateChooser();
        txtDataNascimentoInscrito = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaInscrito = new javax.swing.JTable();
        botaoLimparCampos = new javax.swing.JButton();
        botaoAlterar = new javax.swing.JButton();
        botaoApagar = new javax.swing.JButton();
        campoCpfInscrito = new javax.swing.JFormattedTextField();
        botaoImportar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setTitle("Cadastro de Inscrito");
        jInternalFrame1.setVisible(true);

        campoNomeInscrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeInscritoActionPerformed(evt);
            }
        });
        campoNomeInscrito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoNomeInscritoKeyTyped(evt);
            }
        });

        jLabelNomeInscrito.setText("Nome inscrito:");

        jLabelEmailInscrito.setText("Informe seu email:");

        jLabelCpfInscrito.setText("Informe seu CPF:");

        botaoCadastrar.setText("Cadastrar Inscrito");
        botaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarActionPerformed(evt);
            }
        });

        campoVoltarInscrito.setText("Voltar");
        campoVoltarInscrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoVoltarInscritoActionPerformed(evt);
            }
        });

        jLabelNaturalidadeInscrito.setText("Informe sua naturalidade:");

        jLabelInstituicaoInscrito.setText("Informe sua Instituição:");

        txtDataNascimentoInscrito.setText("Data de nascimento:");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        tabelaInscrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Nome", "CPF"
            }
        ));
        tabelaInscrito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaInscritoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaInscrito);

        botaoLimparCampos.setText("Limpar Campos");

        botaoAlterar.setText("Alterar Inscrito");
        botaoAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAlterarActionPerformed(evt);
            }
        });

        botaoApagar.setText("Apagar Inscrito");
        botaoApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoApagarActionPerformed(evt);
            }
        });

        try {
            campoCpfInscrito.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        botaoImportar.setText("Importar");
        botaoImportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoImportarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(campoVoltarInscrito)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoImportar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoApagar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoAlterar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCpfInscrito)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNomeInscrito)
                                    .addComponent(jLabelEmailInscrito)))
                            .addComponent(jLabelNaturalidadeInscrito)
                            .addComponent(jLabelInstituicaoInscrito)
                            .addComponent(txtDataNascimentoInscrito))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoDataNascimentoInscrito, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoInstituicaoInscrito, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                            .addComponent(campoNaturalidadeInscrito, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                            .addComponent(campoEmailInscrito, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                            .addComponent(campoNomeInscrito, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                            .addComponent(campoCpfInscrito))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(botaoLimparCampos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoCadastrar)
                        .addGap(32, 32, 32))))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoNomeInscrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNomeInscrito))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoEmailInscrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelEmailInscrito))
                        .addGap(6, 6, 6)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCpfInscrito)
                            .addComponent(campoCpfInscrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNaturalidadeInscrito)
                            .addComponent(campoNaturalidadeInscrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelInstituicaoInscrito)
                            .addComponent(campoInstituicaoInscrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDataNascimentoInscrito)
                            .addComponent(campoDataNascimentoInscrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoCadastrar)
                            .addComponent(botaoLimparCampos)))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoVoltarInscrito)
                            .addComponent(botaoAlterar)
                            .addComponent(botaoApagar)
                            .addComponent(botaoImportar))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoVoltarInscritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoVoltarInscritoActionPerformed
        TelaEventos telaEventos = new TelaEventos();
        telaEventos.setVisible(true);
        dispose();
    }//GEN-LAST:event_campoVoltarInscritoActionPerformed

    private void campoNomeInscritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeInscritoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomeInscritoActionPerformed

    private void botaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarActionPerformed
        try {     
        boolean resultado = true;
        resultado = verificarCampos();
        if(resultado == true) {
        inscritoService.incluirInscrito(campoNomeInscrito.getText(), campoCpfInscrito.getText(),campoInstituicaoInscrito.getText() , 
                campoNaturalidadeInscrito.getText(), campoDataNascimentoInscrito.getDate(), campoEmailInscrito.getText());
        LimparCampos();
        AtualizarTabela();
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Preencha todos os campos Corretamente!");
        }
    }//GEN-LAST:event_botaoCadastrarActionPerformed
    int idSelecionado = 0;
    private void botaoApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoApagarActionPerformed
        inscritoService.apagarInscrito(idSelecionado);
        AtualizarTabela();
        LimparCampos();
    }//GEN-LAST:event_botaoApagarActionPerformed

    private void botaoAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAlterarActionPerformed
        inscritoService.alterarInscrito(idSelecionado, campoNomeInscrito.getText(), campoCpfInscrito.getText(),campoInstituicaoInscrito.getText() , 
                campoNaturalidadeInscrito.getText(), campoDataNascimentoInscrito.getDate(), campoEmailInscrito.getText());
        LimparCampos();
        AtualizarTabela();
    }//GEN-LAST:event_botaoAlterarActionPerformed

    private void tabelaInscritoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaInscritoMouseClicked
        Inscrito inscrito = new Inscrito();
        idSelecionado = 
        (int)tabelaInscrito.getValueAt(tabelaInscrito.getSelectedRow(),0);
        inscrito = inscritoService.retornarInscrito(idSelecionado);
          campoNomeInscrito.setText(inscrito.getNome());
        campoEmailInscrito.setText(inscrito.getEmail());
        campoCpfInscrito.setText(inscrito.getCpf());
        campoNaturalidadeInscrito.setText(inscrito.getNaturalidade());
        campoInstituicaoInscrito.setText(inscrito.getInstituicao());
        campoDataNascimentoInscrito.setDate(inscrito.getDataNascimento());
        botaoCadastrar.setEnabled(false);
        botaoApagar.setEnabled(true);
        botaoAlterar.setEnabled(true);
    }//GEN-LAST:event_tabelaInscritoMouseClicked

    private void campoNomeInscritoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoNomeInscritoKeyTyped
       String caracteres="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
        if(!caracteres.contains(evt.getKeyChar()+"")){
        evt.consume();
        }
        
    }//GEN-LAST:event_campoNomeInscritoKeyTyped

    private void botaoImportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoImportarActionPerformed
        new ImportarInscritosExcel().setVisible(true);
    }//GEN-LAST:event_botaoImportarActionPerformed
private void AtualizarTabela() {
      List <Inscrito> listaInscrito = new ArrayList();   
        listaInscrito = inscritoService.listarInscrito() ;
        DefaultTableModel model = (DefaultTableModel) tabelaInscrito.getModel();  
        model.setRowCount(0);
       
        for (Inscrito i : listaInscrito) {   
            Object[] linha = new Object[]{i.getId(), i.getNome(), i.getCpf()};
            model.addRow(linha);
            
        } 
}
     
public boolean verificarCampos() {
        boolean resultado = true;
        if(campoNomeInscrito.getText().equals("") || campoCpfInscrito.getText().equals("") || campoEmailInscrito.getText().equals("")
                || campoInstituicaoInscrito.getText().equals("") || campoNaturalidadeInscrito.getText().equals("")
                || campoDataNascimentoInscrito.getDate().equals(null)) {
            
            resultado = false;
            JOptionPane.showMessageDialog(rootPane, "Preencha todos os campos corretamente");
        }
        return resultado;
    }
       
 private void LimparCampos() {
        campoNomeInscrito.setText("");
        campoEmailInscrito.setText("");
        campoCpfInscrito.setText("");
        campoNaturalidadeInscrito.setText("");
        campoInstituicaoInscrito.setText("");
        campoDataNascimentoInscrito.setDate(null);
        botaoCadastrar.setEnabled(true);
        botaoApagar.setEnabled(false);
        botaoAlterar.setEnabled(false);
        
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarInscrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarInscrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarInscrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarInscrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarInscrito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAlterar;
    private javax.swing.JButton botaoApagar;
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JButton botaoImportar;
    private javax.swing.JButton botaoLimparCampos;
    private javax.swing.JFormattedTextField campoCpfInscrito;
    private com.toedter.calendar.JDateChooser campoDataNascimentoInscrito;
    private javax.swing.JTextField campoEmailInscrito;
    private javax.swing.JTextField campoInstituicaoInscrito;
    private javax.swing.JTextField campoNaturalidadeInscrito;
    private javax.swing.JTextField campoNomeInscrito;
    private javax.swing.JButton campoVoltarInscrito;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabelCpfInscrito;
    private javax.swing.JLabel jLabelEmailInscrito;
    private javax.swing.JLabel jLabelInstituicaoInscrito;
    private javax.swing.JLabel jLabelNaturalidadeInscrito;
    private javax.swing.JLabel jLabelNomeInscrito;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tabelaInscrito;
    private javax.swing.JLabel txtDataNascimentoInscrito;
    // End of variables declaration//GEN-END:variables
}
