/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Evento;
import model.Inscrito;
import model.Ministrante;
import model.Sessao;
import model.TipoSessao;

import service.EventoService;
import service.InscritoService;
import service.MinistranteService;
import service.SessaoService;

/**
 *
 * @author PabloHenrique
 */
public class InformacaoEvento extends javax.swing.JFrame {
    
    /**
     * Creates new form InformaçãoEvento
     */
    public InformacaoEvento(Evento evento) {
        
        initComponents();
        
        campoDataInicio.setMinSelectableDate(Date.from(Instant.now()));
        campoDataFim.setMinSelectableDate(Date.from(Instant.now()));
        preencherEvento(evento);        
        DesabilitarCamposEvento();
        Sessao s = new Sessao();
        BoxTipoSessao.addItem(s.getTipoSessao().MINICURSO);
        BoxTipoSessao.addItem(s.getTipoSessao().PALESTRA);
        AtualizarTabelaSessao();
        listaMinistrante = ministranteService.listarMinistrante();
        while(listaMinistrante.size() > cont) {
        boxMinistrante.addItem(listaMinistrante.get(cont).getNome());
        cont++;
        }
        cont = 0;
        listaInscrito = inscritoService.listarInscrito();
        while(listaInscrito.size() > cont) {
        boxInscrito.addItem(listaInscrito.get(cont).getNome());
        cont++;
        }
    }
    
  
    
    private SessaoService sessaoService = new SessaoService();
    private MinistranteService ministranteService = new MinistranteService();
    private InscritoService inscritoService = new InscritoService();
    private EventoService eventoService = new EventoService();
    
    private InformacaoEvento() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDtFim = new javax.swing.JLabel();
        txtConteudoEmail = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoConteudoEmail = new javax.swing.JTextArea();
        txtNome = new javax.swing.JLabel();
        txtLocal = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        campoLocal = new javax.swing.JTextField();
        txtDtInicio = new javax.swing.JLabel();
        botaoAlterarEvento = new javax.swing.JButton();
        botaoApagarEvento = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        botaoVoltar = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        BotaoCadastrarSessao = new javax.swing.JButton();
        botaoLimparCampos = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaSessao = new javax.swing.JTable();
        botaoAlterarSessao = new javax.swing.JButton();
        botaoApagarSessao = new javax.swing.JButton();
        campoLocalSessao = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        campoHoraFimSessao = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        campoNomeSessao = new javax.swing.JTextField();
        campoNumeroInscritos = new javax.swing.JTextField();
        BoxTipoSessao = new javax.swing.JComboBox();
        campoDataSessao = new com.toedter.calendar.JDateChooser();
        campoHoraInicioSessao = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabelaInscrito = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        boxInscrito = new javax.swing.JComboBox();
        botaoRemoverInscrito = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        boxMinistrante = new javax.swing.JComboBox();
        botaoAdicionarMinistrante = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaMinistrante = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        botaoremoverMinistrantes = new javax.swing.JButton();
        botaoCurriculo = new javax.swing.JButton();
        campoDataInicio = new com.toedter.calendar.JDateChooser();
        campoDataFim = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtDtFim.setText("Data de Fim:");

        txtConteudoEmail.setText("Conteúdo do Email:");

        campoConteudoEmail.setColumns(20);
        campoConteudoEmail.setRows(5);
        jScrollPane1.setViewportView(campoConteudoEmail);

        txtNome.setText("Nome do Evento:");

        txtLocal.setText("Local do Evento:");

        txtDtInicio.setText("Data de Inicio:");

        botaoAlterarEvento.setText("Alterar Evento");
        botaoAlterarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAlterarEventoActionPerformed(evt);
            }
        });

        botaoApagarEvento.setText("Apagar Evento");
        botaoApagarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoApagarEventoActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel2.setText("Informações do Evento");

        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        jLabel10.setText("Número Máximo de Inscritos:");

        BotaoCadastrarSessao.setText("Cadastrar Sessão");
        BotaoCadastrarSessao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastrarSessaoActionPerformed(evt);
            }
        });

        botaoLimparCampos.setText("Limpar Campos");
        botaoLimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparCamposActionPerformed(evt);
            }
        });

        tabelaSessao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Local", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaSessao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaSessaoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaSessao);

        botaoAlterarSessao.setText("Alterar Sessão");
        botaoAlterarSessao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAlterarSessaoActionPerformed(evt);
            }
        });

        botaoApagarSessao.setText("Apagar Sessão");
        botaoApagarSessao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoApagarSessaoActionPerformed(evt);
            }
        });

        campoLocalSessao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoLocalSessaoActionPerformed(evt);
            }
        });

        jLabel6.setText("Horario de Inicio:");

        jLabel7.setText("Horário de Fim:");

        jLabel8.setText("Data:");

        jLabel3.setText("Nome da Sessão:");

        jLabel4.setText("Local da Sessão:");

        jLabel5.setText("Tipo de Sessão:");

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel1.setText("Informações das Sessões");

        campoNumeroInscritos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNumeroInscritosActionPerformed(evt);
            }
        });

        BoxTipoSessao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione um Tipo..." }));

        campoDataSessao.setMinSelectableDate(new java.util.Date(-62135755086000L));

        campoHoraInicioSessao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        campoHoraInicioSessao.setText("  :  ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel8)
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(campoHoraInicioSessao, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(1, 1, 1)
                        .addComponent(campoHoraFimSessao, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoDataSessao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BoxTipoSessao, 0, 157, Short.MAX_VALUE))
                        .addGap(41, 41, 41)
                        .addComponent(jLabel10)
                        .addGap(18, 27, Short.MAX_VALUE)
                        .addComponent(campoNumeroInscritos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(botaoApagarSessao)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoAlterarSessao)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(botaoLimparCampos)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BotaoCadastrarSessao))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(22, 22, 22)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel4))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(campoLocalSessao, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                                                .addComponent(campoNomeSessao)))))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(134, 134, 134)
                                    .addComponent(jLabel1)))
                            .addGap(9, 9, 9))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BoxTipoSessao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(campoHoraFimSessao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoHoraInicioSessao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(campoDataSessao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(campoNumeroInscritos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(170, 170, 170))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(campoNomeSessao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(campoLocalSessao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(jLabel5)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 226, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BotaoCadastrarSessao)
                        .addComponent(botaoLimparCampos)
                        .addComponent(botaoAlterarSessao)
                        .addComponent(botaoApagarSessao))
                    .addContainerGap()))
        );

        jTabbedPane2.addTab("Sessão", jPanel1);

        tabelaInscrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Cpf", "Email", "Instituição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaInscrito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaInscritoMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tabelaInscrito);

        jLabel19.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel19.setText("Informações de Inscritos");

        jLabel11.setText("Inscritos: ");

        boxInscrito.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione um Inscrito..." }));
        boxInscrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxInscritoActionPerformed(evt);
            }
        });

        botaoRemoverInscrito.setText("Remover Inscrito");
        botaoRemoverInscrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRemoverInscritoActionPerformed(evt);
            }
        });

        jButton1.setText("Adicionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoRemoverInscrito)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(27, 27, 27)
                                .addComponent(boxInscrito, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)))
                        .addGap(27, 27, 27)
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(boxInscrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(47, 47, 47)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 241, Short.MAX_VALUE)
                .addComponent(botaoRemoverInscrito)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Inscrito", jPanel3);

        jLabel9.setText("Ministrantes:");

        boxMinistrante.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione um Ministrante..." }));

        botaoAdicionarMinistrante.setText("Adicionar");
        botaoAdicionarMinistrante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAdicionarMinistranteActionPerformed(evt);
            }
        });

        tabelaMinistrante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Email", "Telefone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelaMinistrante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMinistranteMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelaMinistrante);

        jLabel14.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel14.setText("Informações de Ministrantes");

        jLabel15.setText("Currículo:");

        jButton9.setText("Finalizar Cadastro");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        botaoremoverMinistrantes.setText("Remover Ministrante");
        botaoremoverMinistrantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoremoverMinistrantesActionPerformed(evt);
            }
        });

        botaoCurriculo.setText("Ver Curriculo");
        botaoCurriculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCurriculoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botaoremoverMinistrantes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jLabel14)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(boxMinistrante, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoAdicionarMinistrante)
                .addGap(34, 34, 34))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoCurriculo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(boxMinistrante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoAdicionarMinistrante))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(botaoCurriculo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 247, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(botaoremoverMinistrantes))
                .addGap(19, 19, 19))
        );

        jTabbedPane2.addTab("Ministrantes", jPanel2);

        campoDataInicio.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                campoDataInicioPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoApagarEvento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoAlterarEvento)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(campoDataFim, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(campoDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addGap(110, 110, 110)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane2)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNome)
                                    .addComponent(txtLocal))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campoLocal, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                                    .addComponent(campoNome)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDtInicio)
                                    .addComponent(txtDtFim))
                                .addGap(304, 304, 304)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtConteudoEmail)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane1)))
                    .addContainerGap(670, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115)
                .addComponent(campoDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(campoDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoAlterarEvento)
                    .addComponent(botaoApagarEvento)
                    .addComponent(botaoVoltar))
                .addContainerGap())
            .addComponent(jTabbedPane2)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(73, 73, 73)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNome)
                        .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtLocal)
                        .addComponent(campoLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(txtDtInicio)
                    .addGap(18, 18, 18)
                    .addComponent(txtDtFim)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtConteudoEmail)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(195, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

 //------------------------------------Evento----------------------------------------//   
    
    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        TelaEventos telaEventos = new TelaEventos();
        telaEventos.setVisible(true);
        dispose();
    }//GEN-LAST:event_botaoVoltarActionPerformed
        
    private void botaoApagarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoApagarEventoActionPerformed
        eventoService.apagarEvento(id);
        TelaEventos telaEventos = new TelaEventos();
        telaEventos.setVisible(true);
        dispose();
    }//GEN-LAST:event_botaoApagarEventoActionPerformed

    private void botaoAlterarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAlterarEventoActionPerformed
        if (habilitado == false) {
            HabilitarCamposEvento();
        } else {
            eventoService.alterarEvento(id, campoNome.getText(), campoLocal.getText(), campoDataInicio.getDate(), campoDataFim.getDate(), campoConteudoEmail.getText());
            DesabilitarCamposEvento();
            habilitado = false;
            JOptionPane.showMessageDialog(rootPane, "Evento Alterado com Sucesso!");
        }
    }//GEN-LAST:event_botaoAlterarEventoActionPerformed

    private void campoLocalSessaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoLocalSessaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoLocalSessaoActionPerformed

    //--------------------------Sessão------------------------------------
    
    
    private void BotaoCadastrarSessaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastrarSessaoActionPerformed
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm");  
        String horaInicio = campoHoraInicioSessao.getText();  
        String horaFim = campoHoraFimSessao.getText();
        int numeroMaxInscritos = Integer.valueOf(campoNumeroInscritos.getText());
        Date horaInicioSessao = null;  
        Date horaFimSessao = null;
        
        try {
            horaInicioSessao = sdf.parse(horaInicio);
            horaFimSessao = sdf.parse(horaFim);  
        } catch (ParseException ex) {
            Logger.getLogger(InformacaoEvento.class.getName()).log(Level.SEVERE, null, ex);
        }
      
        if (BoxTipoSessao.getSelectedItem().equals(TipoSessao.PALESTRA)) {
            sessaoService.incluirMinistrante(campoNomeSessao.getText(),campoLocalSessao.getText(), TipoSessao.PALESTRA, 
            horaInicioSessao, horaFimSessao,campoDataSessao.getDate(), numeroMaxInscritos, e, listaMinistranteFinal, listaInscritoFinal);    
        } else if(BoxTipoSessao.getSelectedItem().equals(TipoSessao.MINICURSO)) {
            sessaoService.incluirMinistrante(campoNomeSessao.getText(),campoLocalSessao.getText(), TipoSessao.MINICURSO, 
            horaInicioSessao, horaFimSessao,campoDataSessao.getDate(), numeroMaxInscritos, e, listaMinistranteFinal, listaInscritoFinal);    
        }        
        AtualizarTabelaSessao();
        LimparCamposSessao();
    }//GEN-LAST:event_BotaoCadastrarSessaoActionPerformed

    private void botaoLimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparCamposActionPerformed
        LimparCamposSessao();
        BotaoCadastrarSessao.setEnabled(true);  
    }//GEN-LAST:event_botaoLimparCamposActionPerformed
    
    private void tabelaSessaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaSessaoMouseClicked
        LimparCamposSessao();
        Sessao sessao = new Sessao();
        idSelecionadoSessao = 
        (int)tabelaSessao.getValueAt(tabelaSessao.getSelectedRow(),0);
        sessao = sessaoService.retornarSessao(idSelecionadoSessao);
        
        String horaInicio = null;
        String horaFim = null;
        
        try {
              
            horaInicio = new SimpleDateFormat("HH:mm").format(sessao.getHoraInicio());
            horaFim = new SimpleDateFormat("HH:mm").format(sessao.getHoraFim());
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao Converter a Hora para String! " + e);
        }
        campoNomeSessao.setText(sessao.getNome());
        campoLocalSessao.setText(sessao.getLocal());
        String numeroInscritos = String.valueOf(sessao.getNumeroMaximo());
        campoNumeroInscritos.setText(numeroInscritos);
        campoDataSessao.setDate(sessao.getData());
        campoHoraInicioSessao.setText(horaInicio);
        campoHoraFimSessao.setText(horaFim);
        BoxTipoSessao.setSelectedItem(sessao.getTipoSessao());
        BotaoCadastrarSessao.setEnabled(false);
        botaoAlterarSessao.setEnabled(true);
        botaoApagarSessao.setEnabled(true);
        AtualizarTabelaMinistrante();
        AtualizarTabelaInscrito();
    }//GEN-LAST:event_tabelaSessaoMouseClicked

    private void campoNumeroInscritosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNumeroInscritosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNumeroInscritosActionPerformed

    private void botaoApagarSessaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoApagarSessaoActionPerformed
        sessaoService.apagarSessao(idSelecionadoSessao);
        AtualizarTabelaSessao();
        LimparCamposSessao();
        BotaoCadastrarSessao.setEnabled(true);
        idSelecionadoSessao = 0;
        
    }//GEN-LAST:event_botaoApagarSessaoActionPerformed

    private void botaoAlterarSessaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAlterarSessaoActionPerformed
        listaMinistranteFinal.addAll(listaChaveMinistrante);
        listaInscritoFinal.addAll(listaChaveInscrito);
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm");  
        String horaInicio = campoHoraInicioSessao.getText();  
        String horaFim = campoHoraFimSessao.getText();
        int numeroMaxInscritos = Integer.valueOf(campoNumeroInscritos.getText());
        Date horaInicioSessao = null;  
        Date horaFimSessao = null;
        try {
            horaInicioSessao = sdf.parse(horaInicio);
            horaFimSessao = sdf.parse(horaFim);  
        } catch (ParseException ex) {
            Logger.getLogger(InformacaoEvento.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(listaMinistranteFinal.isEmpty() == true) {
            listaMinistranteFinal.addAll(listaMinistrante);
        }
        if(listaInscritoFinal.isEmpty() == true) {
            listaInscritoFinal.addAll(listaInscrito);
        }
        
        if (BoxTipoSessao.getSelectedItem().equals(TipoSessao.PALESTRA)) {
            sessaoService.alterarSessao(idSelecionadoSessao, campoNomeSessao.getText(),campoLocalSessao.getText(), TipoSessao.PALESTRA, 
            horaInicioSessao, horaFimSessao,campoDataSessao.getDate(), numeroMaxInscritos, e,listaMinistranteFinal, listaInscritoFinal );    
        } else if(BoxTipoSessao.getSelectedItem().equals(TipoSessao.MINICURSO)) {
            sessaoService.alterarSessao(idSelecionadoSessao, campoNomeSessao.getText(),campoLocalSessao.getText(), TipoSessao.MINICURSO, 
            horaInicioSessao, horaFimSessao,campoDataSessao.getDate(), numeroMaxInscritos, e,listaMinistranteFinal, listaInscritoFinal);    
        }        
        AtualizarTabelaSessao();
        LimparCamposSessao();
        BotaoCadastrarSessao.setEnabled(true);
        idSelecionadoSessao = 0;
    }//GEN-LAST:event_botaoAlterarSessaoActionPerformed

    //----------------------------------------Ministrantes-----------------------------------------
    
    private void botaoAdicionarMinistranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdicionarMinistranteActionPerformed
        boolean ministrantesLista = false;
        listaChaveMinistrante.removeAll(listaChaveMinistrante);//Limpa a lista Chave.
       
        if(idSelecionadoSessao > 0) {
            listaMinistrante.removeAll(listaMinistrante);// Limpa a listaMinistrante.     
            listaChaveMinistrante.addAll(ministranteService.listarMinistrantePorSessao(idSelecionadoSessao));//Recebe os Ministrantes já cadastrados na sessão.            
            listaMinistranteFinal.addAll(listaChaveMinistrante);//Adiciona os Ministrantes na listaTabela;
            listaMinistrante.addAll(ministranteService.listarMinistrante());//Recebe todos os Ministrantes Cadastrados.
            listaMinistrante.removeAll(listaChaveMinistrante);//Remove todos os ministrantes ja cadastrados dessa sessão.
            listaMinistrante.removeAll(listaAuxiliarMinistrante);//Remove os novos ministrantes a serem cadastrados.
            
            if(listaMinistranteFinal.size() > 0) {
                ministrantesLista = true;
                cont =0;
                while(listaMinistrante.size() > cont) {
                    if(boxMinistrante.getSelectedItem().equals(listaMinistrante.get(cont).getNome())) {
                        listaMinistranteFinal.add(listaMinistrante.get(cont));//Adiciona na listaTabela o novo ministrante a ser cadastrado.
                    }
            
                cont++;
                }    
            } else {
                ministrantesLista = false;
            }
       } 
        if (ministrantesLista == false){ 
            cont = 0;
            listaMinistrante = ministranteService.listarMinistrante();
            listaMinistrante.removeAll(listaAuxiliarMinistrante);
            while(listaMinistrante.size() > cont) {
                if(boxMinistrante.getSelectedItem().equals(listaMinistrante.get(cont).getNome())) {
                    listaMinistranteFinal.add(listaMinistrante.get(cont));
                    listaMinistrante.remove(cont);
                    
            }
            
            cont++;
       }
        }
       cont = 0;
       
        while (listaMinistranteFinal.size() > cont) {
            DefaultTableModel model = (DefaultTableModel) tabelaMinistrante.getModel();  
            model.setRowCount(cont);
            Object[] linha = new Object[]{listaMinistranteFinal.get(cont).getId(), listaMinistranteFinal.get(cont).getNome(), listaMinistranteFinal.get(cont).getEmail(), listaMinistranteFinal.get(cont).getTelefone()};
            model.addRow(linha);
            
            cont++;
       }
        listaAuxiliarMinistrante.removeAll(listaAuxiliarMinistrante);
        listaAuxiliarMinistrante.addAll(listaMinistranteFinal);//Recebe todos os ministrantes que estao na Tabela.
        listaMinistranteFinal.removeAll(listaChaveMinistrante);//Remove da lista os Ministrantes que já foram cadastrado na sessão.
        
    }//GEN-LAST:event_botaoAdicionarMinistranteActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void tabelaMinistranteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMinistranteMouseClicked
        Ministrante ministrante = new Ministrante();
        idSelecionadoMinistrante = 
        (int)tabelaMinistrante.getValueAt(tabelaMinistrante.getSelectedRow(),0);
        ministrante = ministranteService.retornarMinistrante(idSelecionadoMinistrante);
        curriculo = ministrante.getCurriculo();
    }//GEN-LAST:event_tabelaMinistranteMouseClicked

    private void botaoremoverMinistrantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoremoverMinistrantesActionPerformed
            listaMinistrante = ministranteService.listarMinistrantePorSessao(idSelecionadoSessao);
            cont = 0;    
            while (listaMinistrante.size() >  cont) {
                if(listaMinistrante.get(cont).getId() == idSelecionadoMinistrante) {
                    ministranteService.apagarMinistrantePorSessao(idSelecionadoMinistrante);
                    listaChaveMinistrante.remove(listaMinistrante.get(cont));        
                    listaMinistrante.remove(cont);
                }        
                cont++;
            }        
            ((DefaultTableModel) tabelaMinistrante.getModel()).removeRow(tabelaMinistrante.getSelectedRow());   
            cont = 0;
            while(listaMinistranteFinal.size() > cont) {
                if(listaMinistranteFinal.get(cont).getId() == idSelecionadoMinistrante) {
                    listaAuxiliarMinistrante.remove(cont);
                    listaMinistranteFinal.remove(listaMinistranteFinal.get(cont));
                }
            cont++;
            }
             
    }//GEN-LAST:event_botaoremoverMinistrantesActionPerformed
    
    private void botaoCurriculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCurriculoActionPerformed
        CurriculoMinistrante cm = new CurriculoMinistrante(this, true, curriculo);
        cm.setModal(true);
        cm.setVisible(true);
    }//GEN-LAST:event_botaoCurriculoActionPerformed

//-----------------------------------------Inscrito-----------------------------------
      
    private void botaoRemoverInscritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRemoverInscritoActionPerformed
         listaInscrito = inscritoService.listarInscritoPorSessao(idSelecionadoSessao);
            cont = 0;    
            while (listaInscrito.size() >  cont) {
                if(listaInscrito.get(cont).getId() == idSelecionadoInscrito) {
                    inscritoService.apagarInscritoPorSessao(idSelecionadoInscrito);
                    listaChaveInscrito.remove(listaInscrito.get(cont));
                    listaInscrito.remove(cont);
                }        
                cont++;
            }        
            ((DefaultTableModel) tabelaInscrito.getModel()).removeRow(tabelaInscrito.getSelectedRow());   
            cont = 0;
            while(listaInscritoFinal.size() > cont) {
                if(listaInscritoFinal.get(cont).getId() == idSelecionadoInscrito) {
                    listaAuxiliarInscrito.remove(cont);
                    listaInscritoFinal.remove(listaInscritoFinal.get(cont));
                }
            cont++;
            }
    }//GEN-LAST:event_botaoRemoverInscritoActionPerformed

    private void tabelaInscritoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaInscritoMouseClicked
        Inscrito inscrito = new Inscrito();
        idSelecionadoInscrito = 
        (int)tabelaInscrito.getValueAt(tabelaInscrito.getSelectedRow(),0);
        inscrito = inscritoService.retornarInscrito(idSelecionadoInscrito);
    }//GEN-LAST:event_tabelaInscritoMouseClicked

    private void boxInscritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxInscritoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxInscritoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
boolean inscritoLista = false;
        listaChaveInscrito.removeAll(listaChaveInscrito);//Limpa a lista Chave.
       
        if(idSelecionadoSessao > 0) {
            listaInscrito.removeAll(listaInscrito);// Limpa a listaMinistrante.     
            listaChaveInscrito.addAll(inscritoService.listarInscritoPorSessao(idSelecionadoSessao));//Recebe os Ministrantes já cadastrados na sessão.            
            listaInscritoFinal.addAll(listaChaveInscrito);//Adiciona os Ministrantes na listaTabela;
            listaInscrito.addAll(inscritoService.listarInscrito());//Recebe todos os Ministrantes Cadastrados.
            listaInscrito.removeAll(listaChaveInscrito);//Remove todos os ministrantes ja cadastrados dessa sessão.
            listaInscrito.removeAll(listaAuxiliarInscrito);//Remove os novos ministrantes a serem cadastrados.
            
            if(listaInscritoFinal.size() > 0) {
                inscritoLista = true;
                cont =0;
                while(listaInscrito.size() > cont) {
                    if(boxInscrito.getSelectedItem().equals(listaInscrito.get(cont).getNome())) {
                        listaInscritoFinal.add(listaInscrito.get(cont));//Adiciona na listaTabela o novo ministrante a ser cadastrado.
                    }
            
                cont++;
                }    
            } else {
                inscritoLista = false;
            }
       } 
        if (inscritoLista == false){ 
            cont = 0;
            listaInscrito = inscritoService.listarInscrito();
            listaInscrito.removeAll(listaAuxiliarInscrito);
            while(listaInscrito.size() > cont) {
                if(boxInscrito.getSelectedItem().equals(listaInscrito.get(cont).getNome())) {
                    listaInscritoFinal.add(listaInscrito.get(cont));
                    listaInscrito.remove(cont);
                    
            }
            
            cont++;
       }
        }
       cont = 0;
       
        while (listaInscritoFinal.size() > cont) {
            DefaultTableModel model = (DefaultTableModel) tabelaInscrito.getModel();  
            model.setRowCount(cont);
            Object[] linha = new Object[]{listaInscritoFinal.get(cont).getId(), listaInscritoFinal.get(cont).getNome(),listaInscritoFinal.get(cont).getCpf(), listaInscritoFinal.get(cont).getEmail(), listaInscritoFinal.get(cont).getInstituicao()};
            model.addRow(linha);
            
            cont++;
       }
        listaAuxiliarInscrito.removeAll(listaAuxiliarInscrito);
        listaAuxiliarInscrito.addAll(listaInscritoFinal);//Recebe todos os ministrantes que estao na Tabela.
        listaInscritoFinal.removeAll(listaChaveInscrito);//Remove da lista os Ministrantes que já foram cadastrado na sessão.
                
    }//GEN-LAST:event_jButton1ActionPerformed

    private void campoDataInicioPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_campoDataInicioPropertyChange
        campoDataFim.setMinSelectableDate(campoDataInicio.getDate());
    }//GEN-LAST:event_campoDataInicioPropertyChange
    

//---------------------------------------Declaração das Váriaveis e Listas-------------------------------------
    String curriculo = null;    
    int idSelecionadoMinistrante = 0;    
    int idSelecionadoSessao = 0;
    int idSelecionadoInscrito = 0;
    boolean habilitado = false;
    int cont = 0;
    int id = 0;
    ArrayList<Ministrante> listaMinistranteFinal = new ArrayList<Ministrante>();
    ArrayList<Ministrante> listaAuxiliarMinistrante = new ArrayList<Ministrante>();
    ArrayList<Ministrante> listaChaveMinistrante = new ArrayList<Ministrante>();    
    ArrayList<Ministrante> listaMinistrante = new ArrayList<Ministrante>();
    ArrayList<Inscrito> listaInscrito = new ArrayList<Inscrito>();
    ArrayList<Inscrito> listaInscritoFinal = new ArrayList<Inscrito>();
    ArrayList<Inscrito> listaChaveInscrito = new ArrayList<Inscrito>();
    ArrayList<Inscrito> listaAuxiliarInscrito = new ArrayList<Inscrito>();
    Evento e = new Evento();
    //----------------------------------------Métodos--------------------------------------------------------------
    
      private void preencherEvento(Evento evento){
        e = evento;
        id = evento.getId();
        campoNome.setText(evento.getNome());
        campoLocal.setText(evento.getLocal());
        campoDataInicio.setDate(evento.getDataInicio());
        campoDataFim.setDate(evento.getDataFim());
        campoConteudoEmail.setText(evento.getConteudoEmail());
        campoDataSessao.setMinSelectableDate(e.getDataInicio());
        campoDataSessao.setMaxSelectableDate(e.getDataFim());
    }
    
    private void DesabilitarCamposEvento(){
        campoNome.setEditable(false);
        campoLocal.setEditable(false);
        campoDataInicio.setEnabled(false);
        campoDataFim.setEnabled(false);
        campoConteudoEmail.setEditable(false);
        botaoAlterarSessao.setEnabled(false);
        botaoApagarSessao.setEnabled(false);
                
    }
    
    private boolean HabilitarCamposEvento() {
        habilitado = true;
        campoNome.setEditable(true);
        campoLocal.setEditable(true);
        campoDataInicio.setEnabled(true);
        campoDataFim.setEnabled(true);
        campoConteudoEmail.setEditable(true);
        return habilitado;
    }
    
    private void AtualizarTabelaSessao() {
        List <Sessao> listaSessao = new ArrayList();   
        listaSessao = sessaoService.listarSessao(id) ;
        DefaultTableModel model = (DefaultTableModel) tabelaSessao.getModel();  
        model.setRowCount(0);
       
        for (Sessao s : listaSessao) {   
            Object[] linha = new Object[]{s.getId(), s.getNome(), s.getLocal(), s.getTipoSessao()};
            model.addRow(linha);
            
        } 
        
    }
    private void AtualizarTabelaMinistrante() {    
        listaMinistrante = ministranteService.listarMinistrantePorSessao(idSelecionadoSessao);
        DefaultTableModel model = (DefaultTableModel) tabelaMinistrante.getModel();  
        model.setRowCount(0);
        cont = 0;
        for (Ministrante m : listaMinistrante) {   
            Object[] linha = new Object[]{m.getId(), m.getNome(), m.getEmail(), m.getTelefone()};
            model.addRow(linha);
                        
        }
    }
    
    private void AtualizarTabelaInscrito() {       
        listaInscrito = inscritoService.listarInscritoPorSessao(idSelecionadoSessao);
        DefaultTableModel model = (DefaultTableModel) tabelaInscrito.getModel();  
        model.setRowCount(0);
        cont = 0;
        for (Inscrito i : listaInscrito) {   
            Object[] linha = new Object[]{i.getId(), i.getNome(), i.getCpf(),i.getEmail(), i.getInstituicao()};
            model.addRow(linha);
                        
        }
    }
      
    private void LimparCamposSessao() {
        campoNomeSessao.setText("");
        campoLocalSessao.setText("");
        campoHoraInicioSessao.setText("");
        campoHoraFimSessao.setText("");
        campoNumeroInscritos.setText("");
        campoDataSessao.setDate(null);
        BoxTipoSessao.setSelectedIndex(0);
        idSelecionadoSessao = 0;
        curriculo = "";
        DefaultTableModel modelMinistrante = (DefaultTableModel) tabelaMinistrante.getModel();  
        modelMinistrante.setRowCount(0);
        DefaultTableModel modelInscrito = (DefaultTableModel) tabelaInscrito.getModel();  
        modelInscrito.setRowCount(0);
        listaMinistranteFinal.removeAll(listaMinistranteFinal);
        listaInscritoFinal.removeAll(listaInscritoFinal);
        boxMinistrante.setSelectedIndex(0);
        boxInscrito.setSelectedIndex(0);
        listaAuxiliarMinistrante.removeAll(listaAuxiliarMinistrante);
        listaAuxiliarInscrito.removeAll(listaAuxiliarInscrito);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformacaoEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformacaoEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformacaoEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformacaoEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformacaoEvento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoCadastrarSessao;
    private javax.swing.JComboBox BoxTipoSessao;
    private javax.swing.JButton botaoAdicionarMinistrante;
    private javax.swing.JButton botaoAlterarEvento;
    private javax.swing.JButton botaoAlterarSessao;
    private javax.swing.JButton botaoApagarEvento;
    private javax.swing.JButton botaoApagarSessao;
    private javax.swing.JButton botaoCurriculo;
    private javax.swing.JButton botaoLimparCampos;
    private javax.swing.JButton botaoRemoverInscrito;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JButton botaoremoverMinistrantes;
    private javax.swing.JComboBox boxInscrito;
    private javax.swing.JComboBox boxMinistrante;
    private javax.swing.JTextArea campoConteudoEmail;
    private com.toedter.calendar.JDateChooser campoDataFim;
    private com.toedter.calendar.JDateChooser campoDataInicio;
    private com.toedter.calendar.JDateChooser campoDataSessao;
    private javax.swing.JTextField campoHoraFimSessao;
    private javax.swing.JFormattedTextField campoHoraInicioSessao;
    private javax.swing.JTextField campoLocal;
    private javax.swing.JTextField campoLocalSessao;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoNomeSessao;
    private javax.swing.JTextField campoNumeroInscritos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable tabelaInscrito;
    private javax.swing.JTable tabelaMinistrante;
    private javax.swing.JTable tabelaSessao;
    private javax.swing.JLabel txtConteudoEmail;
    private javax.swing.JLabel txtDtFim;
    private javax.swing.JLabel txtDtInicio;
    private javax.swing.JLabel txtLocal;
    private javax.swing.JLabel txtNome;
    // End of variables declaration//GEN-END:variables
}
